// src/pages/MovimentacaoPage.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { ArrowUpRight, ArrowDownRight, Save, Filter, Calendar } from 'lucide-vue-next';
import { toast } from 'sonner-vue';
import Card from '../components/Card.vue';
import Input from '../components/Input.vue';
import Select from '../components/Select.vue';
import Textarea from '../components/Textarea.vue';
import Button from '../components/Button.vue';
import Badge from '../components/Badge.vue';
import { useMaterialStore } from '../stores/materialStore';
import { useMovimentacaoStore } from '../stores/movimentacaoStore';

const materialStore = useMaterialStore();
const movimentacaoStore = useMovimentacaoStore();

const formData = ref({
  tipo: 'entrada',
  materialCodigo: '',
  quantidade: '',
  responsavel: '',
  observacoes: '',
  data: new Date().toISOString().split('T')[0],
});

// Filtros para histórico
const filters = ref({
  dataInicio: '',
  dataFim: '',
  tipo: 'todos',
  busca: ''
});

const tipoOptions = [
  { value: 'entrada', label: 'Entrada' },
  { value: 'saida', label: 'Saída' },
];

const materialOptions = computed(() => [
  { value: '', label: 'Selecione um material...' },
  ...materialStore.materials.map(m => ({ 
    value: m.codigo, 
    label: `${m.nome} (${m.codigo}) - Estoque: ${m.quantidade}` 
  }))
]);

const materialSelecionado = computed(() => 
  materialStore.materials.find(m => m.codigo === formData.value.materialCodigo)
);

const handleSubmit = () => {
  if (!materialSelecionado.value) {
    toast.error('Selecione um material válido');
    return;
  }

  const quantidade = parseInt(formData.value.quantidade);
  
  // Validar quantidade para saída
  if (formData.value.tipo === 'saida' && quantidade > materialSelecionado.value.quantidade) {
    toast.error('Quantidade de saída maior que o estoque disponível!');
    return;
  }

  // Adicionar movimentação
  movimentacaoStore.addMovimentacao({
    tipo: formData.value.tipo as 'entrada' | 'saida',
    materialCodigo: formData.value.materialCodigo,
    materialNome: materialSelecionado.value.nome,
    quantidade: quantidade,
    responsavel: formData.value.responsavel,
    observacoes: formData.value.observacoes,
    data: formData.value.data,
    valor: materialSelecionado.value.valor ? materialSelecionado.value.valor * quantidade : undefined,
    categoria: materialSelecionado.value.categoria
  });

  // Atualizar estoque
  const novaQuantidade = formData.value.tipo === 'entrada' 
    ? materialSelecionado.value.quantidade + quantidade
    : materialSelecionado.value.quantidade - quantidade;

  materialStore.updateMaterial(formData.value.materialCodigo, {
    quantidade: novaQuantidade
  });

  toast.success('Movimentação registrada com sucesso!', {
    description: `${formData.value.tipo === 'entrada' ? 'Entrada' : 'Saída'} de ${quantidade} unidade(s)`
  });

  // Resetar formulário
  formData.value = {
    tipo: 'entrada',
    materialCodigo: '',
    quantidade: '',
    responsavel: '',
    observacoes: '',
    data: new Date().toISOString().split('T')[0],
  };
};

// Histórico filtrado
const historicoFiltrado = computed(() => {
  let resultado = movimentacaoStore.movimentacoes;

  // Filtro por busca
  if (filters.value.busca) {
    const busca = filters.value.busca.toLowerCase();
    resultado = resultado.filter(m => 
      m.materialNome.toLowerCase().includes(busca) ||
      m.materialCodigo.toLowerCase().includes(busca) ||
      m.responsavel.toLowerCase().includes(busca)
    );
  }

  // Filtro por tipo
  if (filters.value.tipo !== 'todos') {
    resultado = resultado.filter(m => m.tipo === filters.value.tipo);
  }

  // Filtro por data
  if (filters.value.dataInicio) {
    resultado = resultado.filter(m => m.data >= filters.value.dataInicio);
  }
  if (filters.value.dataFim) {
    resultado = resultado.filter(m => m.data <= filters.value.dataFim);
  }

  // Ordenar por data (mais recente primeiro)
  return resultado.sort((a, b) => new Date(b.data).getTime() - new Date(a.data).getTime());
});

const limparFiltros = () => {
  filters.value = {
    dataInicio: '',
    dataFim: '',
    tipo: 'todos',
    busca: ''
  };
};
</script>

<template>
  <div class="flex flex-col gap-10">
    <div class="space-y-3">
      <h1 class="bg-gradient-to-r from-[#1E40AF] to-[#2563EB] bg-clip-text text-transparent">
        Movimentação de Estoque
      </h1>
      <p class="text-[#6B7280]">Registre entradas e saídas de materiais</p>
    </div>

    <!-- Formulário de Movimentação -->
    <form @submit.prevent="handleSubmit">
      <div class="flex flex-col gap-8">
        <Card>
          <div class="flex items-center gap-3 mb-8">
            <div class="w-1.5 h-7 bg-gradient-to-b from-[#2563EB] to-[#1E40AF] rounded-full"></div>
            <h3 class="font-semibold text-[#111827]">Nova Movimentação</h3>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Select
              v-model="formData.tipo"
              label="Tipo de Movimentação *"
              :options="tipoOptions"
              required
            />

            <Select
              v-model="formData.materialCodigo"
              label="Material *"
              :options="materialOptions"
              required
            />

            <Input
              v-model="formData.quantidade"
              label="Quantidade *"
              type="number"
              placeholder="0"
              min="1"
              required
            />

            <Input
              v-model="formData.data"
              label="Data *"
              type="date"
              required
            />

            <Input
              v-model="formData.responsavel"
              label="Responsável *"
              placeholder="Nome do responsável"
              required
            />

            <!-- Info do material selecionado -->
            <div v-if="materialSelecionado" class="md:col-span-2 p-4 bg-[#EFF6FF] rounded-xl">
              <div class="flex items-center justify-between">
                <div>
                  <p class="text-sm text-[#6B7280] mb-1">Material Selecionado</p>
                  <p class="font-semibold text-[#111827]">{{ materialSelecionado.nome }}</p>
                  <p class="text-sm text-[#6B7280]">Estoque atual: {{ materialSelecionado.quantidade }} unidades</p>
                </div>
                <Badge :variant="materialSelecionado.quantidade < materialSelecionado.minimo ? 'warning' : 'success'">
                  {{ materialSelecionado.quantidade < materialSelecionado.minimo ? 'BAIXO' : 'OK' }}
                </Badge>
              </div>
            </div>

            <div class="md:col-span-2">
              <Textarea
                v-model="formData.observacoes"
                label="Observações"
                placeholder="Informações adicionais sobre a movimentação"
                :rows="3"
              />
            </div>
          </div>
        </Card>

        <Card class="bg-gradient-to-r from-[#F9FAFB] to-[#F3F4F6] border-2 border-dashed border-[#E5E7EB]">
          <div class="flex justify-end">
            <Button type="submit">
              <Save :size="16" />
              Registrar Movimentação
            </Button>
          </div>
        </Card>
      </div>
    </form>

    <!-- Histórico de Movimentações -->
    <Card>
      <div class="flex items-center gap-3 mb-6">
        <div class="w-12 h-12 bg-[#ECFDF5] rounded-xl flex items-center justify-center">
          <Calendar :size="24" class="text-[#10B981]" />
        </div>
        <div>
          <h3 class="font-semibold text-[#111827]">Histórico de Movimentações</h3>
          <p class="text-sm text-[#6B7280]">{{ historicoFiltrado.length }} movimentações encontradas</p>
        </div>
      </div>

      <!-- Filtros -->
      <div class="mb-6 p-4 bg-[#F8F9FA] rounded-xl">
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-3">
          <Input
            v-model="filters.busca"
            placeholder="Buscar por material ou responsável..."
          />

          <Input
            v-model="filters.dataInicio"
            type="date"
            label="Data Início"
          />

          <Input
            v-model="filters.dataFim"
            type="date"
            label="Data Fim"
          />

          <Select
            v-model="filters.tipo"
            label="Tipo"
            :options="[
              { value: 'todos', label: 'Todos' },
              { value: 'entrada', label: 'Entrada' },
              { value: 'saida', label: 'Saída' }
            ]"
          />
        </div>
        <Button variant="ghost" size="sm" @click="limparFiltros">
          Limpar Filtros
        </Button>
      </div>

      <!-- Tabela Desktop -->
      <div class="hidden lg:block overflow-x-auto">
        <table class="w-full">
          <thead class="bg-[#F8F9FA] border-b border-[#E5E7EB]">
            <tr>
              <th class="px-6 py-4 text-left text-xs font-semibold text-[#6B7280] uppercase tracking-wider">Data</th>
              <th class="px-6 py-4 text-left text-xs font-semibold text-[#6B7280] uppercase tracking-wider">Tipo</th>
              <th class="px-6 py-4 text-left text-xs font-semibold text-[#6B7280] uppercase tracking-wider">Material</th>
              <th class="px-6 py-4 text-left text-xs font-semibold text-[#6B7280] uppercase tracking-wider">Código</th>
              <th class="px-6 py-4 text-left text-xs font-semibold text-[#6B7280] uppercase tracking-wider">Qtd</th>
              <th class="px-6 py-4 text-left text-xs font-semibold text-[#6B7280] uppercase tracking-wider">Responsável</th>
              <th class="px-6 py-4 text-left text-xs font-semibold text-[#6B7280] uppercase tracking-wider">Valor</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-[#F1F3F5]">
            <tr
              v-for="mov in historicoFiltrado"
              :key="mov.id"
              class="hover:bg-[#F8F9FA] transition-colors"
            >
              <td class="px-6 py-4 text-[#6B7280]">
                {{ new Date(mov.data).toLocaleDateString('pt-BR') }}
              </td>
              <td class="px-6 py-4">
                <Badge :variant="mov.tipo === 'entrada' ? 'success' : 'error'">
                  {{ mov.tipo === 'entrada' ? 'ENTRADA' : 'SAÍDA' }}
                </Badge>
              </td>
              <td class="px-6 py-4 font-medium text-[#111827]">{{ mov.materialNome }}</td>
              <td class="px-6 py-4 text-[#6B7280] font-mono text-sm">{{ mov.materialCodigo }}</td>
              <td class="px-6 py-4">
                <span 
                  class="font-bold"
                  :class="mov.tipo === 'entrada' ? 'text-[#10B981]' : 'text-[#EF4444]'"
                >
                  {{ mov.tipo === 'entrada' ? '+' : '-' }}{{ mov.quantidade }}
                </span>
              </td>
              <td class="px-6 py-4 text-[#6B7280]">{{ mov.responsavel }}</td>
              <td class="px-6 py-4 text-[#6B7280]">
                {{ mov.valor ? `R$ ${mov.valor.toFixed(2)}` : '-' }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Cards Mobile -->
      <div class="lg:hidden space-y-4">
        <Card
          v-for="mov in historicoFiltrado"
          :key="mov.id"
          size="small"
        >
          <div class="flex items-start gap-4 mb-4">
            <div 
              class="w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0"
              :class="mov.tipo === 'entrada' ? 'bg-[#ECFDF5] text-[#10B981]' : 'bg-[#FEF2F2] text-[#EF4444]'"
            >
              <component :is="mov.tipo === 'entrada' ? ArrowUpRight : ArrowDownRight" :size="24" />
            </div>
            <div class="flex-1">
              <div class="flex items-start justify-between mb-2">
                <div>
                  <p class="font-semibold text-[#111827]">{{ mov.materialNome }}</p>
                  <p class="text-sm text-[#6B7280]">{{ mov.materialCodigo }}</p>
                </div>
                <Badge :variant="mov.tipo === 'entrada' ? 'success' : 'error'">
                  {{ mov.tipo === 'entrada' ? 'ENTRADA' : 'SAÍDA' }}
                </Badge>
              </div>
            </div>
          </div>
          
          <div class="grid grid-cols-2 gap-3 text-sm">
            <div>
              <span class="text-[#9CA3AF]">Data:</span>
              <span class="ml-2 text-[#111827]">{{ new Date(mov.data).toLocaleDateString('pt-BR') }}</span>
            </div>
            <div>
              <span class="text-[#9CA3AF]">Qtd:</span>
              <span 
                class="ml-2 font-bold"
                :class="mov.tipo === 'entrada' ? 'text-[#10B981]' : 'text-[#EF4444]'"
              >
                {{ mov.tipo === 'entrada' ? '+' : '-' }}{{ mov.quantidade }}
              </span>
            </div>
            <div class="col-span-2">
              <span class="text-[#9CA3AF]">Responsável:</span>
              <span class="ml-2 text-[#111827]">{{ mov.responsavel }}</span>
            </div>
          </div>
        </Card>
      </div>

      <!-- Mensagem vazia -->
      <div v-if="historicoFiltrado.length === 0" class="text-center py-12">
        <p class="text-[#9CA3AF]">Nenhuma movimentação encontrada</p>
      </div>
    </Card>
  </div>
</template>

// src/pages/MovimentacaoPage.tsx
import React, { useState } from 'react';
import { Card } from '../components/Card';
import { Input } from '../components/Input';
import { Select } from '../components/Select';
import { Textarea } from '../components/Textarea';
import { Button } from '../components/Button';
import { Badge } from '../components/Badge';
import { ArrowUpRight, ArrowDownRight, Save, X, Package } from 'lucide-react';

interface MovimentacaoPageProps {
  onNavigate: (page: string) => void;
}

export function MovimentacaoPage({ onNavigate }: MovimentacaoPageProps) {
  const [formData, setFormData] = useState({
    itemId: '',
    tipoMovimentacao: 'entrada',
    quantidade: '',
    motivo: '',
    data: new Date().toISOString().split('T')[0],
    observacoes: '',
  });

  const [itemSelecionado, setItemSelecionado] = useState<any>(null);

  const itens = [
    { value: '', label: 'Selecione um item...' },
    { value: '1', label: 'Notebook Dell Latitude 5420' },
    { value: '2', label: 'Monitor LG 27" 4K' },
    { value: '3', label: 'Mouse Logitech MX Master 3' },
    { value: '4', label: 'Teclado Mecânico Keychron K2' },
    { value: '5', label: 'SSD Samsung 1TB' },
  ];

  const tiposMovimentacao = [
    { value: 'entrada', label: 'Entrada' },
    { value: 'saida', label: 'Saída' },
  ];

  const motivos = {
    entrada: [
      { value: '', label: 'Selecione o motivo...' },
      { value: 'compra', label: 'Compra/Aquisição' },
      { value: 'devolucao', label: 'Devolução' },
      { value: 'transferencia', label: 'Transferência entre locais' },
      { value: 'doacao', label: 'Doação' },
      { value: 'outros', label: 'Outros' },
    ],
    saida: [
      { value: '', label: 'Selecione o motivo...' },
      { value: 'distribuicao', label: 'Distribuição/Alocação' },
      { value: 'manutencao', label: 'Manutenção' },
      { value: 'descarte', label: 'Descarte' },
      { value: 'transferencia', label: 'Transferência entre locais' },
      { value: 'emprestimo', label: 'Empréstimo' },
      { value: 'outros', label: 'Outros' },
    ],
  };

  // Mockup de dados do item selecionado
  const mockItems: any = {
    '1': {
      nome: 'Notebook Dell Latitude 5420',
      codigo: 'PAT-2024-001',
      categoria: 'Notebooks',
      quantidadeAtual: 45,
      quantidadeMinima: 20,
      local: 'Almoxarifado 1',
      foto: 'https://via.placeholder.com/150',
    },
    '2': {
      nome: 'Monitor LG 27" 4K',
      codigo: 'PAT-2024-002',
      categoria: 'Monitores',
      quantidadeAtual: 12,
      quantidadeMinima: 15,
      local: 'TI - Prédio A',
      foto: 'https://via.placeholder.com/150',
    },
  };

  const handleItemSelect = (itemId: string) => {
    setFormData({ ...formData, itemId });
    if (itemId && mockItems[itemId]) {
      setItemSelecionado(mockItems[itemId]);
    } else {
      setItemSelecionado(null);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    alert(`Movimentação de ${formData.tipoMovimentacao} registrada com sucesso!`);
    onNavigate('dashboard');
  };

  const getQuantidadeResultante = () => {
    if (!itemSelecionado || !formData.quantidade) return itemSelecionado?.quantidadeAtual || 0;
    
    const qtd = parseInt(formData.quantidade);
    const atual = itemSelecionado.quantidadeAtual;
    
    if (formData.tipoMovimentacao === 'entrada') {
      return atual + qtd;
    } else {
      return Math.max(0, atual - qtd);
    }
  };

  const motivosOptions = formData.tipoMovimentacao === 'entrada' ? motivos.entrada : motivos.saida;

  return (
    <div className="flex flex-col gap-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-[#111827] mb-1">Movimentação de Estoque</h1>
        <p className="text-[#6B7280]">Registre entradas e saídas de materiais</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Formulário - 2 colunas */}
        <div className="lg:col-span-2">
          <form onSubmit={handleSubmit} className="flex flex-col gap-6">
            {/* Seção 1: Tipo de Movimentação */}
            <Card>
              <h3 className="font-semibold text-[#111827] mb-4">Tipo de Movimentação</h3>
              
              <div className="grid grid-cols-2 gap-3">
                <button
                  type="button"
                  onClick={() => setFormData({ ...formData, tipoMovimentacao: 'entrada', motivo: '' })}
                  className={`
                    h-24 rounded-lg border-2 transition-all flex flex-col items-center justify-center gap-2
                    ${formData.tipoMovimentacao === 'entrada'
                      ? 'border-[#10B981] bg-[#ECFDF5] text-[#10B981]'
                      : 'border-[#E5E7EB] bg-white text-[#6B7280] hover:border-[#D1D5DB]'
                    }
                  `}
                >
                  <ArrowUpRight className="w-8 h-8" />
                  <span className="font-medium">Entrada</span>
                </button>
                
                <button
                  type="button"
                  onClick={() => setFormData({ ...formData, tipoMovimentacao: 'saida', motivo: '' })}
                  className={`
                    h-24 rounded-lg border-2 transition-all flex flex-col items-center justify-center gap-2
                    ${formData.tipoMovimentacao === 'saida'
                      ? 'border-[#EF4444] bg-[#FEF2F2] text-[#EF4444]'
                      : 'border-[#E5E7EB] bg-white text-[#6B7280] hover:border-[#D1D5DB]'
                    }
                  `}
                >
                  <ArrowDownRight className="w-8 h-8" />
                  <span className="font-medium">Saída</span>
                </button>
              </div>
            </Card>

            {/* Seção 2: Seleção do Item */}
            <Card>
              <h3 className="font-semibold text-[#111827] mb-4">Selecionar Item</h3>
              
              <Select
                label="Item do Estoque *"
                options={itens}
                value={formData.itemId}
                onChange={(e) => handleItemSelect(e.target.value)}
                required
              />
            </Card>

            {/* Seção 3: Detalhes da Movimentação */}
            <Card>
              <h3 className="font-semibold text-[#111827] mb-4">Detalhes da Movimentação</h3>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Input
                  label="Quantidade *"
                  type="number"
                  placeholder="0"
                  min="1"
                  max={formData.tipoMovimentacao === 'saida' ? itemSelecionado?.quantidadeAtual : undefined}
                  value={formData.quantidade}
                  onChange={(e) => setFormData({ ...formData, quantidade: e.target.value })}
                  required
                />

                <Input
                  label="Data *"
                  type="date"
                  value={formData.data}
                  onChange={(e) => setFormData({ ...formData, data: e.target.value })}
                  required
                />

                <div className="md:col-span-2">
                  <Select
                    label="Motivo da Movimentação *"
                    options={motivosOptions}
                    value={formData.motivo}
                    onChange={(e) => setFormData({ ...formData, motivo: e.target.value })}
                    required
                  />
                </div>

                <div className="md:col-span-2">
                  <Textarea
                    label="Observações"
                    placeholder="Informações adicionais sobre a movimentação (opcional)"
                    value={formData.observacoes}
                    onChange={(e) => setFormData({ ...formData, observacoes: e.target.value })}
                    rows={3}
                  />
                </div>
              </div>
            </Card>

            {/* Botões de Ação */}
            <Card className="bg-[#F9FAFB]">
              <div className="flex flex-col sm:flex-row items-center justify-end gap-3">
                <Button 
                  type="button" 
                  variant="secondary"
                  onClick={() => onNavigate('dashboard')}
                >
                  <X className="w-4 h-4" />
                  Cancelar
                </Button>
                <Button type="submit">
                  <Save className="w-4 h-4" />
                  Registrar Movimentação
                </Button>
              </div>
            </Card>
          </form>
        </div>

        {/* Painel Lateral - Resumo do Item - 1 coluna */}
        <div className="lg:col-span-1">
          <Card className="sticky top-20">
            <div className="flex items-center gap-2 mb-4">
              <Package className="w-5 h-5 text-[#6B7280]" />
              <h3 className="font-semibold text-[#111827]">Resumo do Item</h3>
            </div>
            
            {itemSelecionado ? (
              <div className="flex flex-col gap-4">
                {/* Foto */}
                <img 
                  src={itemSelecionado.foto}
                  alt={itemSelecionado.nome}
                  className="w-full h-40 object-cover rounded-lg border border-[#E5E7EB]"
                />
                
                {/* Informações */}
                <div>
                  <h4 className="font-medium text-[#111827] mb-1">
                    {itemSelecionado.nome}
                  </h4>
                  <p className="text-sm text-[#6B7280] mb-3">
                    {itemSelecionado.categoria} • {itemSelecionado.codigo}
                  </p>
                  
                  <div className="flex flex-col gap-2">
                    <div className="flex justify-between py-2 border-b border-[#E5E7EB]">
                      <span className="text-sm text-[#6B7280]">Local</span>
                      <span className="text-sm font-medium text-[#111827]">
                        {itemSelecionado.local}
                      </span>
                    </div>
                    
                    <div className="flex justify-between py-2 border-b border-[#E5E7EB]">
                      <span className="text-sm text-[#6B7280]">Qtd. Atual</span>
                      <span className="text-sm font-medium text-[#111827]">
                        {itemSelecionado.quantidadeAtual}
                      </span>
                    </div>
                    
                    <div className="flex justify-between py-2 border-b border-[#E5E7EB]">
                      <span className="text-sm text-[#6B7280]">Qtd. Mínima</span>
                      <span className="text-sm font-medium text-[#111827]">
                        {itemSelecionado.quantidadeMinima}
                      </span>
                    </div>
                    
                    {formData.quantidade && (
                      <div className="flex justify-between py-2 mt-2 bg-[#F9FAFB] rounded-lg px-3">
                        <span className="text-sm font-medium text-[#111827]">Qtd. Resultante</span>
                        <span className={`
                          text-sm font-bold
                          ${formData.tipoMovimentacao === 'entrada' 
                            ? 'text-[#10B981]' 
                            : 'text-[#EF4444]'
                          }
                        `}>
                          {getQuantidadeResultante()}
                        </span>
                      </div>
                    )}
                  </div>
                </div>
                
                {/* Alerta se ficar abaixo do mínimo */}
                {formData.quantidade && 
                 getQuantidadeResultante() < itemSelecionado.quantidadeMinima && (
                  <Card variant="warning" size="small">
                    <p className="text-xs text-[#92400E]">
                      ⚠️ Esta movimentação deixará o estoque abaixo do mínimo recomendado.
                    </p>
                  </Card>
                )}
                
                {/* Alerta se quantidade insuficiente */}
                {formData.tipoMovimentacao === 'saida' && 
                 formData.quantidade && 
                 parseInt(formData.quantidade) > itemSelecionado.quantidadeAtual && (
                  <Card variant="error" size="small">
                    <p className="text-xs text-[#991B1B]">
                      ❌ Quantidade insuficiente em estoque.
                    </p>
                  </Card>
                )}
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-12 text-center">
                <Package className="w-12 h-12 text-[#D1D5DB] mb-3" />
                <p className="text-sm text-[#9CA3AF]">
                  Selecione um item para visualizar as informações
                </p>
              </div>
            )}
          </Card>
        </div>
      </div>
    </div>
  );
}
