// src/App.tsx
import React, { useState } from 'react';
import { Header } from './components/Header';
import { Sidebar } from './components/Sidebar';
import { LoginPage } from './pages/LoginPage';
import { DashboardPage } from './pages/DashboardPage';
import { CadastroPage } from './pages/CadastroPage';
import { ListagemPage } from './pages/ListagemPage';
import { EdicaoPage } from './pages/EdicaoPage';
import { MovimentacaoPage } from './pages/MovimentacaoPage';
import { AlertasPage } from './pages/AlertasPage';
import { RelatoriosPage } from './pages/RelatoriosPage';
import { ConfiguracoesPage } from './pages/ConfiguracoesPage';
import { MaterialProvider } from './contexts/MaterialContext';
import { Toaster } from 'sonner';
import { motion, AnimatePresence } from 'motion/react';

export default function App() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [currentPage, setCurrentPage] = useState('dashboard');
  const [currentItemId, setCurrentItemId] = useState<number | undefined>();
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);

  const handleLogin = () => {
    setIsAuthenticated(true);
    setCurrentPage('dashboard');
  };

  const handleLogout = () => {
    setIsAuthenticated(false);
    setCurrentPage('dashboard');
    setSidebarOpen(false);
  };

  const handleNavigate = (page: string, itemId?: number) => {
    setCurrentPage(page);
    setCurrentItemId(itemId);
    setSidebarOpen(false);
  };

  // Renderizar página de login se não autenticado
  if (!isAuthenticated) {
    return <LoginPage onLogin={handleLogin} />;
  }

  // Renderizar página atual
  const renderPage = () => {
    switch (currentPage) {
      case 'dashboard':
        return <DashboardPage onNavigate={handleNavigate} />;
      case 'cadastro':
        return <CadastroPage onNavigate={handleNavigate} />;
      case 'listagem':
        return <ListagemPage onNavigate={handleNavigate} />;
      case 'edicao':
        return <EdicaoPage onNavigate={handleNavigate} itemId={currentItemId} />;
      case 'movimentacao':
        return <MovimentacaoPage onNavigate={handleNavigate} />;
      case 'alertas':
        return <AlertasPage onNavigate={handleNavigate} />;
      case 'relatorios':
        return <RelatoriosPage onNavigate={handleNavigate} />;
      case 'configuracoes':
        return <ConfiguracoesPage onLogout={handleLogout} />;
      default:
        return <DashboardPage onNavigate={handleNavigate} />;
    }
  };

  return (
    <MaterialProvider>
      <div className="min-h-screen bg-gradient-to-br from-[#F9FAFB] via-[#F3F4F6] to-[#F9FAFB]">
        <Toaster position="top-right" richColors closeButton />
        
        {/* Header */}
        <Header 
          onMenuClick={() => setSidebarOpen(!sidebarOpen)}
          userName="João Silva"
        />

        {/* Sidebar */}
        <Sidebar
          isOpen={sidebarOpen}
          onClose={() => setSidebarOpen(false)}
          currentPage={currentPage}
          onNavigate={handleNavigate}
          isCollapsed={sidebarCollapsed}
          onToggleCollapse={() => setSidebarCollapsed(!sidebarCollapsed)}
        />

        {/* Main Content com animação de transição de página */}
        <main 
          className={`pt-16 transition-all duration-300 ${sidebarCollapsed ? 'lg:pl-20' : 'lg:pl-72'}`}
        >
          <div className="container max-w-[1200px] py-8 lg:py-10">
            <AnimatePresence mode="wait">
              <motion.div
                key={currentPage}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                transition={{ duration: 0.3, ease: "easeInOut" }}
              >
                {renderPage()}
              </motion.div>
            </AnimatePresence>
          </div>
        </main>
      </div>
    </MaterialProvider>
  );
}

// src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Toaster } from 'vue-sonner';
import Header from './components/Header.vue';
import Sidebar from './components/Sidebar.vue';
import DashboardPage from './pages/DashboardPage.vue';
import CadastroPage from './pages/CadastroPage.vue';
import ListagemPage from './pages/ListagemPage.vue';
import MovimentacaoPage from './pages/MovimentacaoPage.vue';
import AlertasPage from './pages/AlertasPage.vue';
import RelatoriosPage from './pages/RelatoriosPage.vue';
import ConfiguracoesPage from './pages/ConfiguracoesPage.vue';
import LoginPage from './pages/LoginPage.vue';
import EdicaoPage from './pages/EdicaoPage.vue'; // <--- IMPORTAÇÃO NOVA OBRIGATÓRIA

const isAuthenticated = ref(true);
const currentPage = ref('dashboard');
const isSidebarOpen = ref(false);
const isSidebarCollapsed = ref(false);

const handleLogin = () => {
  isAuthenticated.value = true;
  currentPage.value = 'dashboard';
};

const handleNavigate = (page: string) => {
  currentPage.value = page;
  isSidebarOpen.value = false;
};

const toggleSidebar = () => {
  isSidebarOpen.value = !isSidebarOpen.value;
};

const toggleSidebarCollapse = () => {
  isSidebarCollapsed.value = !isSidebarCollapsed.value;
};
</script>

<template>
  <div>
    <Toaster 
      position="top-right" 
      :rich-colors="true" 
      :duration="3000"
      :theme="'light'"
    />
    
    <LoginPage v-if="!isAuthenticated" @login="handleLogin" />
    
    <div v-else class="min-h-screen bg-[#F8F9FA]">
      <Header @menu-click="toggleSidebar" user-name="Admin" />
      
      <Sidebar
        :is-open="isSidebarOpen"
        :current-page="currentPage"
        :is-collapsed="isSidebarCollapsed"
        @close="isSidebarOpen = false"
        @navigate="handleNavigate"
        @toggle-collapse="toggleSidebarCollapse"
      />
      
      <main 
        class="pt-24 pb-12 px-6 lg:px-8 transition-all duration-300"
        :class="isSidebarCollapsed ? 'lg:pl-28' : 'lg:pl-80'"
      >
        <div class="max-w-7xl mx-auto">
          <DashboardPage v-if="currentPage === 'dashboard'" @navigate="handleNavigate" />
          <CadastroPage v-else-if="currentPage === 'cadastro'" @navigate="handleNavigate" />
          <ListagemPage v-else-if="currentPage === 'listagem'" @navigate="handleNavigate" />
          
          <EdicaoPage v-else-if="currentPage === 'edicao'" @navigate="handleNavigate" />
          
          <MovimentacaoPage v-else-if="currentPage === 'movimentacao'" @navigate="handleNavigate" />
          <AlertasPage v-else-if="currentPage === 'alertas'" @navigate="handleNavigate" />
          <RelatoriosPage v-else-if="currentPage === 'relatorios'" @navigate="handleNavigate" />
          <ConfiguracoesPage v-else-if="currentPage === 'configuracoes'" @navigate="handleNavigate" />
        </div>
      </main>
    </div>
  </div>
</template>
